version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: farm
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD: placeholder-pw
      PGPORT: 5432
    ports:
      - "127.0.0.1:5432:5432"
  api:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
