version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: farm
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD: placeholder-pw
      PGPORT: 5433
    ports:
      - "5433:5433"
  api:
    build: .
    restart: always
    environment:
      DATABASE: farm
      DATABASE_USERNAME: farmer
      DATABASE_PASSWORD: placeholder-pw
      DB_HOSTNAME: db
      DB_PORT: 5433
      API_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
